services:
  backend:
    # image: pokedex-plus-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    # image: pokedex-plus-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  private-network:
    driver: bridge
  app-network:
    driver: bridge
