name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend build
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  frontend:
    name: Frontend build
    runs-on: ubuntu-24.04
    needs: backend
    defaults:
      run:
        working-directory: frontend/pokedex-plus
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/pokedex-plus/package-lock.json

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/pokedex-plus/.next/cache
          key: nextcache-${{ runner.os }}-v1-${{ hashFiles('frontend/pokedex-plus/package-lock.json', 'frontend/pokedex-plus/package.json', 'frontend/pokedex-plus/next.config.*', 'frontend/pokedex-plus/tsconfig.json', 'frontend/pokedex-plus/.babelrc', 'frontend/pokedex-plus/.env.production') }}
          restore-keys: |
            nextcache-${{ runner.os }}-v1-
            nextcache-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      # - name: Typecheck/Tests
      #   run: |
      #     npm run typecheck --if-present
      #     npm test --if-present

      - name: Next build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "true"
        run: npm run build
