name: Release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release + Docker
    runs-on: ubuntu-latest
    steps:
      - name: Ensure CI succeeded
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Required CI workflow did not succeed. Aborting release."
          exit 1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Semantic Release
        id: semrel
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits

      - name: Extract version parts
        id: version
        if: steps.semrel.outputs.new_release_published == 'true'
        shell: bash
        run: |
          echo "version=${{ steps.semrel.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          ver='${{ steps.semrel.outputs.new_release_version }}'
          major=$(echo "$ver" | awk -F. '{print $1}')
          minor=$(echo "$ver" | awk -F. '{print $2}')
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT

      - name: Docker Login
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # --- BACKEND ---
      - name: Build & Push Backend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            eugiovannicruz/pokedex-plus-backend:${{ steps.version.outputs.version }}
            eugiovannicruz/pokedex-plus-backend:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            eugiovannicruz/pokedex-plus-backend:${{ steps.version.outputs.major }}
            eugiovannicruz/pokedex-plus-backend:latest

      # --- FRONTEND ---
      - name: Build & Push Frontend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/pokedex-plus
          push: true
          tags: |
            eugiovannicruz/pokedex-plus-frontend:${{ steps.version.outputs.version }}
            eugiovannicruz/pokedex-plus-frontend:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            eugiovannicruz/pokedex-plus-frontend:${{ steps.version.outputs.major }}
            eugiovannicruz/pokedex-plus-frontend:latest
