name: Release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release + Docker
    runs-on: ubuntu-latest
    steps:
      - name: Ensure CI succeeded
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Required CI workflow did not succeed. Aborting release."
          exit 1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Semantic Release
        id: semrel
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits

      - name: Extract version parts
        id: version
        if: steps.semrel.outputs.new_release_published == 'true'
        shell: bash
        run: |
          ver='${{ steps.semrel.outputs.new_release_version }}'
          echo "version=$ver" >> $GITHUB_OUTPUT
          major=$(echo "$ver" | cut -d. -f1)
          minor=$(echo "$ver" | cut -d. -f2)
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          # Flag "stable" só se major >= 1
          if [ "$major" -ge 1 ]; then echo "stable=true" >> $GITHUB_OUTPUT; else echo "stable=false" >> $GITHUB_OUTPUT; fi

      - name: Docker Login
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Setup QEMU
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3.6.0

      - name: Setup Buildx
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3.11.1

      # --- BACKEND METADATA ---
      - name: Docker metadata (backend)
        id: meta_backend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/metadata-action@v5.8.0
        with:
          images: docker.io/eugiovannicruz/pokedex-plus-backend
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            type=raw,value=${{ steps.version.outputs.major }}
            ${{ steps.version.outputs.stable == 'true' && 'type=raw,value=latest' || '' }}

      # --- BACKEND BUILD & PUSH ---
      - name: Build & Push Backend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      # --- FRONTEND METADATA ---
      - name: Docker metadata (frontend)
        id: meta_frontend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/metadata-action@v5.8.0
        with:
          images: docker.io/eugiovannicruz/pokedex-plus-frontend
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            type=raw,value=${{ steps.version.outputs.major }}
            ${{ steps.version.outputs.stable == 'true' && 'type=raw,value=latest' || '' }}

      # --- FRONTEND BUILD & PUSH ---
      - name: Build & Push Frontend
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./frontend/pokedex-plus
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
